#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# active window opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8

# disable specific apps
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^计算器$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Moom$" manage=off
yabai -m rule --add app="^Mechvibes$" manage=off
yabai -m rule --add app="^LetsVPN$" manage=off
yabai -m rule --add app="^KeyCastr$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off

echo "yabai configuration loaded.."
