import = ["/Users/zhaorui/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
padding = { x = 10, y = 10 }

[font]
size = 16.0
# bold = 			{ family = "JetBrainsMono Nerd Font", style = "Heavy" }
# bold_italic = 	{ family = "JetBrainsMono Nerd Font", style = "Heavy Italic" }
# italic = 		{ family = "JetBrainsMono Nerd Font", style = "Heavy Medium" }
# normal = 		{ family = "JetBrainsMono Nerd Font", style = "Medium" }

bold = 			{ family = "MesloLGS NF", style = "Bold" }
bold_italic = 	{ family = "MesloLGS NF", style = "Bold Italic" }
italic = 		{ family = "MesloLGS NF", style = "Italic" }
normal = 		{ family = "MesloLGS NF", style = "Regular" }


#[keyboard]
#	{ key = "E", mods = "Command", 			chars = "\u0001-"}, # split tmux window horizontally
#]
