require("zhaorui.config")
require("zhaorui.plugins")

-- require("zhaorui2.plugins-setup")
-- require("zhaorui2.core.options")
-- require("zhaorui2.core.keymaps")
-- require("zhaorui2.core.colorscheme")
-- require("zhaorui2.plugins.comment")
-- require("zhaorui2.plugins.nvim-tree")
-- require("zhaorui2.plugins.lualine")
-- require("zhaorui2.plugins.telescope")
-- require("zhaorui2.plugins.nvim-cmp")
-- require("zhaorui2.plugins.lsp.mason")
-- require("zhaorui2.plugins.lsp.lspsaga")
-- require("zhaorui2.plugins.lsp.lspconfig")
-- require("zhaorui2.plugins.lsp.null-ls")
-- require("zhaorui2.plugins.autopairs")
-- require("zhaorui2.plugins.treesitter")
